### ISSUE TITLE
Share this on the FreeCAD forums?

### ISSUE THREAD

**Issue by luzpaz** [FabLabBaramati/freecadDatumLoacalAxisMacro#1]
Hi! very cool macro!
Have you shared this on the forum.freecad.org scripting subforum (https://forum.freecad.org/viewforum.php?f=22) yet ?

**Comment by FabLabBaramati** [comment]
not yet .  actully using forum new to me  so .  feel free to use anyware .

**Comment by FabLabBaramati** [comment]
[https://forum.freecad.org/viewtopic.php?t=79562](https://forum.freecad.org/viewtopic.php?t=79562 )  shared this on the forum.freecad.org

**Comment by luzpaz** [comment]
Maybe we can add this to https://github.com/FreeCAD/FreeCAD-macros too?

**Comment by FabLabBaramati** [comment]
opened PR- [https://github.com/FreeCAD/FreeCAD-macros/pull/161](https://github.com/FreeCAD/FreeCAD-macros/pull/161)
